Initial setup
BenM4k/react-bookstore pull request #1
Opened 2023-06-05 21:04 UTC by BenM4k

In this initial setup, I:
- Setup a new React application using [Create React App](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app)
- Created a directory for reusable components: /components.
- Installed [React Router V6](https://reactrouter.com/en/main/start/tutorial#setup) and [Setup myrouter](https://reactrouter.com/en/main/start/tutorial#adding-a-router) inside of "App"
- Added 2 routes in my application, each rendering a page component:
 "/" and "/categories"
- Create components inside of the /components directory: "Contains individual book state, as well as a button to delete the book", "Contains a list to renders individual books", "Contains a form to create new books", "Contains a navigation to link to the 2 routes I created"

2023-06-05 21:24 UTC, BenMukebo requested changes
### Hi @BenM4k,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Gitflow was correctly used.  ✔️   
- Your Pull Request has a proper title and description. ✔️  
- There is 2 `<Route>`s added :heavy_check_mark: 
- Contains 2 page components: `<Books>` and `<Categories>`. 👍🏻 
- Your README file looks awesome, keep rocking :rocket: 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 21:24 UTC, BenMukebo commented on package.json
>      "web-vitals": "^2.1.4"
- [ ] Great job so far everything looks fine 👍🏻 , however, I'm getting this error after installing the project dependencies 👇🏻 Please fix this. 👍🏻 

![image](https://github.com/BenM4k/react-bookstore/assets/79058364/8e94f759-fd11-4fff-91c5-9f53472e56ff)

2023-06-06 03:47 UTC, shella12 approved these changes
Hi @BenM4k, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Project is running on the server ✔️ 
- Package error has been fixed 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 04:10 UTC, merged

2023-07-11 09:50 UTC, wayungi reviewed
Hi @BenM4k , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ]  Correct Git flow ✔️ 
- [ ] Descriptive PR body ✔️ 
- [ ] Project up and running ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._